name: jurusanku
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: 2.11.0
  firebase_auth: 4.5.0
  cloud_firestore: 4.6.0
  flutter:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/app/fonts/Poppins-Regular.ttf
        - asset: lib/app/fonts/Poppins-Bold.ttf
        - asset: lib/app/fonts/Poppins-Medium.ttf
  uses-material-design: true
