// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcTbmqdeHIWQowiADLKNcY5jVjDpYIHUQ',
    appId: '1:660396341829:web:9276ab2426db1f984f412c',
    messagingSenderId: '660396341829',
    projectId: 'jurusanku-1c92f',
    authDomain: 'jurusanku-1c92f.firebaseapp.com',
    storageBucket: 'jurusanku-1c92f.appspot.com',
    measurementId: 'G-2RDM8N1019',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeZ0panhE6xQwpsyi6ycvMOULkrn5JMLc',
    appId: '1:660396341829:android:274bbae6e568bb734f412c',
    messagingSenderId: '660396341829',
    projectId: 'jurusanku-1c92f',
    storageBucket: 'jurusanku-1c92f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-DBgmhwcphsFyGGQ_HSnjjm2Lig7S10',
    appId: '1:660396341829:ios:b3ef774c3be039504f412c',
    messagingSenderId: '660396341829',
    projectId: 'jurusanku-1c92f',
    storageBucket: 'jurusanku-1c92f.appspot.com',
    androidClientId: '660396341829-kkmp84etf2nvp2kmdervtku73j5m2nnl.apps.googleusercontent.com',
    iosClientId: '660396341829-va3e31nlv81fo2tvvhqqe6anmvprad60.apps.googleusercontent.com',
    iosBundleId: 'com.revproject.jurusanku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-DBgmhwcphsFyGGQ_HSnjjm2Lig7S10',
    appId: '1:660396341829:ios:b3ef774c3be039504f412c',
    messagingSenderId: '660396341829',
    projectId: 'jurusanku-1c92f',
    storageBucket: 'jurusanku-1c92f.appspot.com',
    androidClientId: '660396341829-kkmp84etf2nvp2kmdervtku73j5m2nnl.apps.googleusercontent.com',
    iosClientId: '660396341829-va3e31nlv81fo2tvvhqqe6anmvprad60.apps.googleusercontent.com',
    iosBundleId: 'com.revproject.jurusanku',
  );
}
